model: "dctcrn"
model_kwargs:
    rnn_layers: 2
    rnn_channels: 256
    N: 512
    hop_size: 128
    win_size: 512
    win_type: "hann"
    masking_mode: "T"   # "P" (PReLU) / "S" (Sigmoid) / "T" (Tanh) / "N" (No mask)
    kernel_size: [5, 2]
    channels: [8, 16, 32, 64, 128, 128, 256]
    use_mdct: False
    norm: "batchnorm"



data:
    clean_dir: "/home/jhkim21/Data/processed/2022_AGC/clean"
    noisy_dir: "/home/jhkim21/Data/processed/2022_AGC/noisy"
    train_idx:
        start: 0
        end: 9499
    valid_idx:
        start: 9500
        end: 9999
    infer_idx: 
        start: 9500
        end : 9999     # 0은 잘되는편, 471은 안되는편
    segment_size: 64000
    sampling_rate: 16000
train:
    batch_size: 128

    max_epochs: 100
    fp16: True
    num_workers: 2
    persistent_workers: True
    clip_grad: null
    seed: 1234
    plot_param_and_grad: False
    save_interval: 50
    infer_interval: 5

    #loss_aux: "abs_mse"
    #lambda_aux: 512.0
    #power: 0.6

    optimizer: "Adam"
    optimizer_kwargs:
        lr: 5e-4
    scheduler: "CosineAnnealingLR"
    scheduler_kwargs:
        T_max: 100
        eta_min: 1.0e-7
