model: "echofilter_like"
model_kwargs:
    rnn_layers: 2
    rnn_channels: 256
    N: 512
    hop_size: 128
    win_size: 512
    win_type: "hann"
    masking_mode: "T"   # "P" (PReLU) / "S" (Sigmoid) / "T" (Tanh) / "N" (No mask)
    kernel_size: [5, 2]
    channels: [8, 16, 32, 64, 128, 128, 256]
    use_mdct: False
    norm: "batchnorm"



data:
    near_dir: "/home/jhkim21/Data/AEC-Challenge/datasets/synthetic/nearend_speech"
    far_dir: "/home/jhkim21/Data/AEC-Challenge/datasets/synthetic/farend_speech"
    mix_dir: "/home/jhkim21/Data/AEC-Challenge/datasets/synthetic/nearend_mic_signal"
    echo_dir: "/home/jhkim21/Data/AEC-Challenge/datasets/synthetic/echo_signal"
    two_way : False
    train_idx:
        start: 500
        end: 9999
    valid_idx:
        start: 0
        end: 499
    infer_idx:    # 0은 잘되는편, 471은 안되는편
        start: 0 
        end: 499
    segment_size: 64000
    sampling_rate: 16000
train:
    batch_size: 32

    max_epochs: 300
    fp16: True
    num_workers: 2
    persistent_workers: True
    clip_grad: null
    seed: 1234
    plot_param_and_grad: False
    save_interval: 50
    infer_interval: 5

    #loss_aux: "abs_mse"
    #lambda_aux: 512.0
    #power: 0.6

    optimizer: "AdamW"
    optimizer_kwargs:
        lr: 0.001
        weight_decay: 0.5
    scheduler: "CosineAnnealingLR"
    scheduler_kwargs:
        T_max: 300
        eta_min: 1.0e-7
